version: '3'

services:
  redis:
    image: redis:alpine
  app:
    image: knesset-data-pipelines
    depends_on:
      - redis
    environment:
      - "DPP_REDIS_HOST=redis"
    ports:
      - "5000:5000"
