{{ if .Values.workersEnabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{.Values.name | default "app"}}-workers
spec:
  replicas: {{ .Values.dppWorkerReplicas | default "3" }}
  strategy: {type: Recreate}
  template:
    metadata:
      labels:
        app: {{.Values.name | default "app"}}-workers
    spec:
      containers:
      - name: {{.Values.name | default "app"}}-workers
        image: {{.Values.image | default "orihoch/knesset-data-pipelines:latest" | quote}}
        args: ["workers"]
        env:
        - {name: DPP_WORKER_CONCURRENCY, value: {{.Values.dppWorkerConcurrency | default "1" | quote}}}
{{ include "app-common-env" . | indent 8}}
        resources:
          requests:
            cpu: {{.Values.cpuRequests | default "0.4"}}
            memory: {{.Values.memoryRequests | default "500Mi" | quote}}
{{ end }}
