app:
  autoscalerBranch: master
  autoscalerGitEmail: knesset-data-production-autoscaler@next.oknesset.org
  autoscalerGitUser: oknesset-deployment-bot
  autoscalerImage: gcr.io/hasadna-oknesset/knesset-data-pipelines-production-app-autoscaler:v1.0.6-224-g431a718-2017-10-18-12-46
  autoscalerInterval: '300'
  autoscalerPipelinesUrl: http://app-serve:5000
  autoscalerRepo: hasadna/knesset-data-pipelines
  autoscalerValuesFile: devops/k8s/values-production-provision.yaml
  cpuRequests: 0.7
  dppWorkerConcurrency: 4
  dppWorkerReplicas: 2
  dppWorkersGkeNodePool: dpp-workers
  enableAutoscaler: true
  enableWorkers: false
  image: gcr.io/hasadna-oknesset/knesset-data-pipelines-production-app:v0.0.0-2017-11-05-18-12
  influxDb: dpp
  memoryRequests: 1800Mi
  sshSocksProxyUrl: socks5h://ssh-socks-proxy:8123
committees:
  enabled: true
  image: gcr.io/hasadna-oknesset/knesset-data-pipelines-committees:v1.0.6-83-g8a136f6-2017-10-05-14-23
db:
  backupUploadBucketName: kdp-production-db-backups
  backupUploadProjectId: hasadna-oknesset
  backupUploadServiceAccountId: kdp-production-db-backups@hasadna-oknesset.iam.gserviceaccount.com
  backupUploadServiceAccountKeySecret: db-backup-upload-google-key
  backupUploadZone: us-central1-a
  dbBackupImage: gcr.io/hasadna-oknesset/knesset-data-pipelines-db-backup:v1.0.6-83-g8a136f6-2017-10-05-14-23
  gcePersistentDiskName: knesset-data-pipelines-production-db
flower:
  urlPrefix: flower
global:
  gkeNodePool: pool-1
  rootUrl: https://next.oknesset.org
  skipInitContainers: true
grafana:
  anonymousEnabled: true
  enabled: true
influxdb:
  enabled: true
  gcePersistentDiskName: knesset-data-pipelines-production-influxdb
jobs:
  restoreDbGsUrl: ''
  restoreDbImage: gcr.io/hasadna-oknesset/knesset-data-pipelines-db-backup:v1.0.6-83-g8a136f6-2017-10-05-14-23
  restoreDbJobName: ''
  restoreDbProjectId: hasadna-oknesset
  restoreDbServiceAccountId: kdp-production-db-backups@hasadna-oknesset.iam.gserviceaccount.com
  restoreDbServiceAccountKeySecret: db-backup-upload-google-key
  restoreDbZone: us-central1-a
letsencrypt:
  enabled: true
metabase:
  enabled: true
  gkeNodePool: metabase-7
minio:
  gcePersistentDiskName: knesset-data-pipelines-production-minio
nginx:
  enableCommittees: true
  enableGrafana: true
  enableMetabase: true
  enabled: true
  htpasswdSecretName: nginx-htpasswd
  minioSslDomain: minio.oknesset.org
  sslDomain: next.oknesset.org
ssh-socks-proxy:
  enabled: true
  socks_port: '8123'
  ssh_host: ubuntu@db1.oknesset.org
  ssh_port: '22'
